# Alternative Konfiguration mit Secrets-Datei
esphome:
  name: "clock-2-0"
  friendly_name: "Clock 2.0"

esp8266:
  board: d1_mini

# WiFi-Konfiguration mit Secrets
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Clock-2-0 Fallback Hotspot"
    password: "12345678"

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

# Home Assistant Zeit-Synchronisation
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Berlin"
    on_time_sync:
      then:
        - logger.log: "Zeit mit Home Assistant synchronisiert"
        - lambda: |-
            ESP_LOGI("time", "Aktuelle Zeit: %s", id(homeassistant_time).now().strftime("%Y-%m-%d %H:%M:%S").c_str());

# LCD 1602 Display-Konfiguration (4-Bit parallel) - Sichere GPIO-Pins
display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - D5  # GPIO14 - sicher
      - D6  # GPIO12 - sicher  
      - D7  # GPIO13 - sicher
      - D1  # GPIO5 - sicher (statt D8/GPIO15)
    enable_pin: D2  # GPIO4 - sicher (statt D3/GPIO0)
    rs_pin: D0      # GPIO16 - sicher (statt D2/GPIO4)
    # rw_pin wird nicht verwendet (an GND)
    lambda: |-
      // Erste Zeile: Datum
      it.strftime(0, 0, "%d.%m.%Y", id(homeassistant_time).now());
      // Zweite Zeile: Uhrzeit  
      it.strftime(0, 1, "%H:%M:%S", id(homeassistant_time).now());

# Status-LED
output:
  - platform: gpio
    pin: D4  # Onboard LED (invertiert)
    id: onboard_led
    inverted: true

light:
  - platform: binary
    name: "Status LED"
    output: onboard_led
    id: status_led

# Sensoren
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
  - platform: version
    name: "ESPHome Version"

button:
  - platform: restart
    name: "Restart"
